#!/usr/bin/env bash
set -e

linepush_file="$HOME/.linepush"

touch "$linepush_file"
source "$linepush_file"

if [ -z "$LINEPUSH_USER_ID" ]; then
    echo "LINEPUSH_USER_ID is not set"
    exit 1
fi

if [ -z "$LINEPUSH_CHANNEL_ACCESS_TOKEN" ]; then
    echo "LINEPUSH_CHANNEL_ACCESS_TOKEN is not set"
    exit 1
fi

message=$1

if [ -z "$message" ]; then
    echo "Message is not set, use: linepush \"message\""
    exit 1
fi

response=$(curl -s -X POST https://api.line.me/v2/bot/message/push \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer ${LINEPUSH_CHANNEL_ACCESS_TOKEN}" \
     -d "{\"to\":\"${LINEPUSH_USER_ID}\",\"messages\":[{\"type\":\"text\",\"text\":\"$message\"}]}")

if [ "$response" != "{}" ]; then
    echo "Error: $response"
    exit 1
fi
